language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - python -m unittest discover